using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Goobstation.Client.CurrencyStore.Managers;
using Content.Goobstation.Common.CCVar;
using Content.Goobstation.Common.ServerCurrency;
using Content.Goobstation.Shared.CurrencyStore.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Goobstation.Client.CurrencyStore.UI;

[GenerateTypedNameReferences]
public sealed partial class CurrencyStoreWindow : FancyWindow
{
    public event Action<BaseButton.ButtonEventArgs, ProtoId<CurrencyStoreCategoryPrototype>>? OnCategoryButtonPressed;

    public ProtoId<CurrencyStoreCategoryPrototype> CurrentCategory = string.Empty;

    public CurrencyStoreWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetBalance(int balance)
    {
        PlayerBalance.Text = Loc.GetString("server-currency-name-amount", ("amount", balance));
    }

    public void PopulateStoreCategories(IEnumerable<CurrencyStoreCategoryPrototype> categories)
    {
        CategoryList.RemoveAllChildren();

        var group = new ButtonGroup();

        foreach (var category in categories)
        {
            if (CurrentCategory == string.Empty)
                CurrentCategory = category;

            var button = new CurrencyStoreCategoryButton
            {
                Text = Loc.GetString(category.Name),
                ToolTip = Loc.GetString(category.Description),
                Pressed = CurrentCategory == category,
                Group = group,
                ToggleMode = true,
                StyleClasses = { "CurrencyStoreTopButton" },
                Id = category.ID,
            };

            button.OnPressed += args => OnCategoryButtonPressed?.Invoke(args, button.Id);

            CategoryList.AddChild(button);
        }
    }

    public void PopulateStoreListings(IEnumerable<CurrencyStoreItemPrototype> items)
    {
        ItemListings.RemoveAllChildren();

        foreach (var item in items)
        {
            var listing = new CurrencyStoreListing(item);

            ItemListings.AddChild(listing);
        }
    }

    private sealed class CurrencyStoreCategoryButton : Button
    {
        public required ProtoId<CurrencyStoreCategoryPrototype> Id;
    }
}
