using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Goobstation.Client.CurrencyStore.Managers;
using Content.Goobstation.Shared.CurrencyStore;
using Content.Goobstation.Shared.CurrencyStore.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Goobstation.Client.CurrencyStore.UI;

[GenerateTypedNameReferences]
public sealed partial class CurrencyStoreWindow : FancyWindow
{
    [Dependency] private readonly IClientCurrencyStoreManager _currencyStore = default!;

    public event Action<BaseButton.ButtonEventArgs, ProtoId<CurrencyStoreCategoryPrototype>>? OnCategoryButtonPressed;
    public event Action<BaseButton.ButtonEventArgs, ProtoId<CurrencyStoreItemPrototype>>? OnPurchaseButtonPressed;

    public ProtoId<CurrencyStoreCategoryPrototype> CurrentCategory = string.Empty;

    public CurrencyStoreWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetBalance(int balance)
    {
        PlayerBalance.Text = Loc.GetString("server-currency-name-amount", ("amount", balance));
    }

    public void UpdateItem(ProtoId<CurrencyStoreItemPrototype> proto, CurrencyStoreItemData data)
    {
        var control = ItemListings.Children
            .FirstOrDefault(c => c is CurrencyStoreItemListing l && l.Prototype == proto);

        if (control is CurrencyStoreItemListing listing)
            listing.SetPrice(data.Price);
    }

    public void PopulateStoreCategories(IEnumerable<CurrencyStoreCategoryPrototype> categories)
    {
        CategoryList.RemoveAllChildren();

        var group = new ButtonGroup();

        foreach (var category in categories)
        {
            if (CurrentCategory == string.Empty)
                CurrentCategory = category;

            var button = new CurrencyStoreCategoryButton
            {
                Text = Loc.GetString(category.Name),
                ToolTip = Loc.GetString(category.Description),
                Pressed = CurrentCategory == category,
                Group = group,
                ToggleMode = true,
                StyleClasses = { "CurrencyStoreTopButton" },
                Id = category.ID,
            };

            button.OnPressed += args => OnCategoryButtonPressed?.Invoke(args, button.Id);

            CategoryList.AddChild(button);
        }
    }

    public void PopulateStoreListings(IEnumerable<CurrencyStoreItemPrototype> items)
    {
        ItemListings.RemoveAllChildren();

        foreach (var item in items)
        {
            var listing = new CurrencyStoreItemListing(item, _currencyStore.GetItemDynamicPrice(item));

            listing.OnPurchaseButtonPressed += (args, proto) => OnPurchaseButtonPressed?.Invoke(args, proto);

            ItemListings.AddChild(listing);
        }
    }

    private sealed class CurrencyStoreCategoryButton : Button
    {
        public required ProtoId<CurrencyStoreCategoryPrototype> Id;
    }
}
