using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Goobstation.Client.CurrencyStore.Managers;
using Content.Goobstation.Common.CCVar;
using Content.Goobstation.Common.ServerCurrency;
using Content.Goobstation.Shared.CurrencyStore.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Goobstation.Client.CurrencyStore.UI;

[GenerateTypedNameReferences]
public sealed partial class CurrencyStoreWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IConfigurationManager _config = default!;
    [Dependency] private readonly ICommonCurrencyManager _currency = default!;
    [Dependency] private readonly IClientCurrencyStoreManager _currencyStore = default!;

    private readonly bool _showHiddenItems;

    private ProtoId<CurrencyStoreCategoryPrototype> _currentCategory = string.Empty;

    public CurrencyStoreWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _showHiddenItems = _config.GetCVar(GoobCVars.CurrencyStoreAllowPurchaseHidden);

        PlayerBalance.Text = $"{_currency.GetBalance()} {Loc.GetString("server-currency-name-abbreviation")}";

        PopulateStoreCategories();
    }

    /// <summary>
    ///     Switch to the specified category
    /// </summary>
    public void SwitchCategory(ProtoId<CurrencyStoreCategoryPrototype> category)
    {
        _currentCategory = category;

        PopulateStoreListings(category);
    }

    private void PopulateStoreCategories()
    {
        var group = new ButtonGroup();
        foreach (var category in _proto.EnumeratePrototypes<CurrencyStoreCategoryPrototype>()
                     .Where(c => c.InStore || _showHiddenItems)
                     .OrderBy(c => c.Priority))
        {
            if (_currentCategory == string.Empty)
                PopulateStoreListings(_currentCategory = category);

            // TODO(XWH): Make CurrencyStoreCategoryButton class with category ID.
            // TODO(XWH): touch stylenano or kill myself | Make this look good with style magic.
            var button = new Button
            {
                Text = Loc.GetString(category.Name),
                ToolTip = Loc.GetString(category.Description),
                Pressed = _currentCategory == category,
                Group = group,
                ToggleMode = true,
                StyleClasses = { "CurrencyStoreTopButton" },
            };

            button.OnPressed += _ => SwitchCategory(category);

            CategoryList.AddChild(button);
        }
    }

    private void PopulateStoreListings(ProtoId<CurrencyStoreCategoryPrototype> category)
    {
        ItemListings.RemoveAllChildren();

        foreach (var item in _proto.EnumeratePrototypes<CurrencyStoreItemPrototype>()
                     .Where(i => i.Category == category && (!i.Permanent || !_currencyStore.CheckPurchasedPermanentItem(i)))
                     .OrderBy(i => Loc.GetString(i.Name))) // TODO(XWH): This might run poorly.
        {
            // TODO(XWH): Pass an ID to this so that we can tell what item it represents for purchasing items.
            var listing = new CurrencyStoreListing();

            listing.PopulatePrototype(item);

            ItemListings.AddChild(listing);
        }
    }

    private sealed class CurrencyStoreCategoryButton : Button
    {
        public string Id = string.Empty;
    }
}
