using Content.Goobstation.Client.CurrencyStore.Managers;
using Content.Goobstation.Shared.CurrencyStore;
using Content.Goobstation.Shared.CurrencyStore.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Goobstation.Client.CurrencyStore.UI;

/// <summary>
///     Generic item listing for the store and inventory windows
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CurrencyStoreListing : PanelContainer
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IClientCurrencyStoreManager _currencyStore = default!;

    public CurrencyStoreListing()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    /// <summary>
    ///     Apply the data in a prototype to the listing.
    /// </summary>
    public void PopulatePrototype(ProtoId<CurrencyStoreItemPrototype> protoId)
    {
        if (!_proto.TryIndex(protoId, out var proto))
            return;

        ItemName.Text = Loc.GetString(proto.Name);
        ItemDescription.Text = Loc.GetString(proto.Description);
        PurchaseButton.Text = $"{proto.Price} {Loc.GetString("server-currency-name-abbreviation")}";

        ItemTraitList.RemoveAllChildren();

        AddTrait(Loc.GetString("currencystore-item-trait-uses", ("uses", proto.MaxUses)));

        if (proto.Immediate)
            AddTrait(Loc.GetString("currencystore-item-trait-immediate"));

        switch (proto.Redeemable)
        {
            case CurrencyStoreRoundState.PreRound:
            {
                AddTrait(Loc.GetString("currencystore-item-trait-redeemable-preround"));
                break;
            }
            case CurrencyStoreRoundState.InRound:
            {
                AddTrait(Loc.GetString("currencystore-item-trait-redeemable-inround"));
                break;
            }
        }

        if (proto.Permanent)
            AddTrait(Loc.GetString("currencystore-item-trait-permanent"));
    }

    private void AddTrait(string text)
    {
        if (ItemTraitList.ChildCount > 0)
            text = " | " + text;

        ItemTraitList.AddChild(new Label { Text = text });
}
}
