using Content.Goobstation.Client.CurrencyStore.Managers;
using Content.Goobstation.Shared.CurrencyStore;
using Content.Goobstation.Shared.CurrencyStore.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Goobstation.Client.CurrencyStore.UI;

/// <summary>
///     Currency store/inventory listing.
/// </summary>
[GenerateTypedNameReferences]
public abstract partial class CurrencyStoreListing : PanelContainer
{
    public CurrencyStoreListing()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    ///     Shared code between <see cref="CurrencyStoreItemListing"/> and <see cref="CurrencyStoreInventoryItemListing"/>
    /// </summary>
    protected void ApplyItemPrototype(CurrencyStoreItemPrototype proto)
    {
        ClearTraits();

        ItemName.Text = Loc.GetString(proto.Name);
        ItemDescription.Text = Loc.GetString(proto.Description);

        if (proto.Immediate)
            AddTrait(Loc.GetString("currencystore-item-trait-immediate"));

        switch (proto.Redeemable)
        {
            case CurrencyStoreRoundState.PreRound:
            {
                AddTrait(Loc.GetString("currencystore-item-trait-redeemable-preround"));
                break;
            }
            case CurrencyStoreRoundState.InRound:
            {
                AddTrait(Loc.GetString("currencystore-item-trait-redeemable-inround"));
                break;
            }
        }

        if (proto.Permanent)
            AddTrait(Loc.GetString("currencystore-item-trait-permanent"));
    }

    /// <summary>
    ///     Clear the trait list
    /// </summary>
    protected void ClearTraits()
    {
        ItemTraitList.RemoveAllChildren();
    }

    /// <summary>
    ///     Add a trait to the trait list
    /// </summary>
    protected void AddTrait(string text)
    {
        if (ItemTraitList.ChildCount > 0)
            text = " | " + text;

        ItemTraitList.AddChild(new Label { Text = text });
    }
}
